[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "https://task-list-chessiah.netlify.app/*"
  to = "https://task-list.chessiah.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://task-list-chessiah.netlify.app/*"
  to = "https://task-list.chessiah.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://task-list.chessiah.com/*"
  to = "https://task-list.chessiah.com/:splat"
  status = 301
  force = true
