[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "https://task-list-aleksey-vl-ivanov.com.netlify.app/*"
  to = "https://task-list.aleksey-vl-ivanov.com.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://task-list-aleksey-vl-ivanov.com.netlify.app/*"
  to = "https://task-list.aleksey-vl-ivanov.com.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://task-list.aleksey-vl-ivanov.com.com/*"
  to = "https://task-list.aleksey-vl-ivanov.com.com/:splat"
  status = 301
  force = true
